project:
  type: website
  output-dir: docs

website:
  title: "Hayes Waddell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Academic Projects
      - href: blog/index.qmd
        text: Baseball Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual




