project:
  type: website
  output-dir: docs

website:
  title: "Hayes Waddell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-science.qmd
        text: Data Science
      - href: neuroscience.qmd
        text: Neuroscience

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual




